#!/bin/bash
#
# Copyright (c) 2012-2014 Message Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This script removes all subscribers that are not "master" or "cluster".
# This is to help release space from the jlog.
# !!! WARNING: USE THIS SCRIPT VERY, VERY CAREFULLY. !!!

# XXX: Support some way of specifying which subscribers to keep.

JLOGCTL=/opt/msys/jlog/bin/jlogctl
DRYRUN=0

if [ "$1" = "-n" -o "$1" = "--dry-run" ]; then
  DRYRUN=1
  shift
fi

JLOG=$1
if [ -z "$1" -o ! -d "$JLOG" ]; then
  echo "Syntax: $0 [-n | --dry-run] <jlog>"
fi

# Do not remove master or cluster subscribers, for safety.
# Users of the script have to do that manually with 'jlogctl'.
subscribers=$(
    $JLOGCTL -s $JLOG \
  | grep -v $JLOG \
  | grep -v master \
  | grep -v cluster \
  | awk '{ print $1 }' \
  | sort -n
)

if [ $DRYRUN = "0" ]; then
  for subs in $subscribers; do
    $JLOGCTL -e $subs $JLOG
    echo
  done
else 
  echo "NOTICE: Running in dry-run mode"
  echo "NOTICE: Subscribers available for removal: $subscribers"
fi

echo "Remaining subscribers:"
$JLOGCTL -s $JLOG

